version: '3.9'

services:
    front_img:
            container_name: CPG_Front
            build: 
                context: ./file
                dockerfile: Vue.Dockerfile
            volumes:
                - C:/Users/ykh05/Desktop/Project/APG/vue:/home/vue
                - C:/Users/ykh05/Desktop/Project/APG/docker/nginx/sites-available:/etc/nginx/sites-available
            ports:
                - "80:80"
                - "3000:3000"
            extra_hosts:
                - "loc.apg.com:172.19.0.10"
            privileged: true
            command: /sbin/init
            user: 0:0
            environment:
                TZ: Asia/Seoul
            networks:
                server_net:
                    ipv4_address: "172.19.0.10"
    back_img:
        container_name: CPG_back
        build: 
            context: ./file
            dockerfile: Spring.Dockerfile
        volumes:
            - C:/Users/ykh05/Desktop/Project/APG/spring:/home/spring
        ports:
            - "8080:8080"
        privileged: true
        command: /sbin/init
        user: 0:0
        environment:
            TZ: Asia/Seoul
        networks:
            server_net:
                ipv4_address: "172.19.0.20"

networks:
    server_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.19.0.0/16"          
